<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="b0b63dca-e0f5-4334-8753-189571fa0b36" name="Shawn@SH-DEV-042 2013-10-10 14:23:57" runUser="SH-DEV-042\Shawn" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Default Test Settings" id="e2bc265c-a5fd-4c95-b969-391a3996b728">
    <Deployment runDeploymentRoot="Shawn_SH-DEV-042 2013-10-10 14_23_57">
      <DeploymentItem filename="C:\Dropbox\Lib\Projects\Voodoo\Voodoo.TestData\Voodoo.TestData\bin\Debug\Voodoo.TestData.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2013-10-10T14:23:57.8907409-05:00" queuing="2013-10-10T14:23:58.8310782-05:00" start="2013-10-10T14:23:58.9431179-05:00" finish="2013-10-10T14:24:35.4732045-05:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="SH-DEV-042" outcome="Error" timestamp="2013-10-10T14:24:35.4722041-05:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="RandomizerDoesNotThrowExceptionsWithRangeAttribute" storage="c:\dropbox\lib\projects\voodoo\voodoo.testdata\voodoo.testdata.tests\bin\debug\voodootestdatatest.dll" id="72cb9780-65ac-e05d-cb7a-d54926f74dd2">
      <Execution id="e03bd371-ed4b-4c1e-8ba8-4e5d173e8d1a" />
      <TestMethod codeBase="C:/Dropbox/Lib/Projects/Voodoo/Voodoo.TestData/Voodoo.TestData.Tests/bin/Debug/VoodooTestDataTest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="VoodooTestDataTest.RandomizerTests, VoodooTestDataTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="RandomizerDoesNotThrowExceptionsWithRangeAttribute" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="72cb9780-65ac-e05d-cb7a-d54926f74dd2" executionId="e03bd371-ed4b-4c1e-8ba8-4e5d173e8d1a" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="e03bd371-ed4b-4c1e-8ba8-4e5d173e8d1a" testId="72cb9780-65ac-e05d-cb7a-d54926f74dd2" testName="RandomizerDoesNotThrowExceptionsWithRangeAttribute" computerName="SH-DEV-042" duration="00:00:36.3760312" startTime="2013-10-10T14:23:59.0971733-05:00" endTime="2013-10-10T14:24:35.4732045-05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e03bd371-ed4b-4c1e-8ba8-4e5d173e8d1a">
    </UnitTestResult>
  </Results>
</TestRun>